service: page-to-pdf
frameworkVersion: '3'
useDotenv: true
provider:
  name: aws
  runtime: python3.9
  layers:
    - arn:aws:lambda:sa-east-1:347599033421:layer:wkhtmltopdf-0_12_6:1
    - arn:aws:lambda:sa-east-1:347599033421:layer:amazon_linux_fonts:1
  environment:
    ENVIRONMENT: ${env:ENVIRONMENT}
    FONTCONFIG_PATH: /opt/etc/fonts
  region: sa-east-1
  stage: homolog
  apiGateway:
    binaryMediaTypes:
      - 'application/pdf'
plugins:
  - serverless-dotenv-plugin
  - serverless-python-requirements
  - serverless-offline
custom:
  pythonRequirements:
    dockerizePip: non-linux
package:
  exclude:
    - node_modules/**
  excludeDevDependencies: true
functions:
  get:
    handler: handler.get
    events:
      - http:
          path: pdf
          method: get
          cors: true
